module2-task2
htmlacademy-nodejs/1693173-buy-and-sell-3 pull request #5
Opened 2021-02-02 07:45 UTC by ruslanshkolnykh

2021-02-02 19:52 UTC, dean992008 requested changes

2021-02-02 19:52 UTC, dean992008 commented on src/service/cli/generate.js
> +    const sentences = await readContent(FILE_SENTENCES_PATH);
Здесь в плане производительности правильно было бы применить `Promise.all` вместо 3 await и после этого диструктуризирует результат. Это позволит сделать паралельный запуск чтения 3 файлов, а не выполянять его последовательно.

2021-02-03 00:26 UTC, ruslanshkolnykh commented on src/service/cli/generate.js
> +    const sentences = await readContent(FILE_SENTENCES_PATH);
добавил

2021-02-03 09:06 UTC, dean992008 requested changes

2021-02-03 09:06 UTC, dean992008 commented on src/service/cli/generate.js
> +    await Promise.all([readContent(FILE_SENTENCES_PATH), readContent(FILE_TITLES_PATH), readContent(FILE_CATEGORIES_PATH)]).then((values) => {
Почти так, но я бы немного по другому сделал: 
```
const [sentences, titles, categories] = await Promise.all([readContent(FILE_SENTENCES_PATH), readContent(FILE_TITLES_PATH), readContent(FILE_CATEGORIES_PATH)]);
```
Это позволит избевится от переменых с let, которые заполняются через замыкание. 
Также чтобы разобраться в теме async/await рекомендую дополнительно прочитать: https://learn.javascript.ru/async-await

2021-02-03 16:26 UTC, merged